
/* Realizacion de un programa que contenga 3 juegos de luces con el uso de arduino en la plataforma de proteus
 *  NOGUERA LEANDRO
 *  20 DE OCTUBRE DEL 2016
 *  DOCENTE: PAUL ROSERO
 * FICA-CIERCOM
 */


int leds[14] ={0,1,2,3,4,5,6,7,8,9,10,11,12,13};//DECLARACION DE UN VECTOR, POR CADA PIN A USAR EN EL ARDUINO 
void setup() {
  //pines digitales 1y 0
  pinMode(1,OUTPUT);//EL PIN 1 ESTA DECLARADO COMO SALIDA
  pinMode(2,OUTPUT);//EL PIN 2 ESTA DECLARADO COMO SALIDA
  pinMode(3,OUTPUT);//EL PIN 3 ESTA DECLARADO COMO SALIDA
  pinMode(4,OUTPUT);//EL PIN 4 ESTA DECLARADO COMO SALIDA
  pinMode(5,OUTPUT);//EL PIN 5 ESTA DECLARADO COMO SALIDA
  pinMode(6,OUTPUT);//EL PIN 6 ESTA DECLARADO COMO SALIDA
  pinMode(7,OUTPUT);//EL PIN 7 ESTA DECLARADO COMO SALIDA
  pinMode(8,OUTPUT);//EL PIN 8 ESTA DECLARADO COMO SALIDA
  pinMode(9,OUTPUT);//EL PIN 9 ESTA DECLARADO COMO SALIDA
  pinMode(10,OUTPUT);//EL PIN 10 ESTA DECLARADO COMO SALIDA
  pinMode(11,OUTPUT);//EL PIN 11 ESTA DECLARADO COMO SALIDA
  pinMode(12,OUTPUT);//EL PIN 12 ESTA DECLARADO COMO SALIDA
  pinMode(13,OUTPUT);//EL PIN 13 ESTA DECLARADO COMO SALIDA
  pinMode(0,OUTPUT);//EL PIN 0 ESTA DECLARADO COMO SALIDA
   
}
void primer_juego()//METODO O CLASE QUE REALIZA EL PRIMER JUEGO DE LUCES DE FORMA ASCENDENTE, ES DECIR DEL PIN 0 AL PIN 13 DEL ARDUINO
{
   int contador=0;//VARIABLE CONTADOR LA CUAL NOS IRA ACUMULANDO EL VALOR DEL CICLO A DECLARAR
  for (;contador<=13;contador++)//CICLO QUE IRA PASANDO POR CADA POSICION DEL ARDUINO
{
  digitalWrite(leds[contador],HIGH);//RESULTADO O SALIDA EN LA BAR LED ENCENDIDO
  delay(200); //RETARDO O TIEMPO DE EJECUCION 
    digitalWrite(leds[contador],LOW);//RESULTADO O SALIDA EN LA BAR LED APAGADO
  delay(200);//RETARDO O TIEMPO DE EJECUCION 

}
}

void tercer_juego()//TERCER JUEGO DE LUCES, CICLO DECREMENTAL DEL VECTOR APAGARA LOS LEDES QUE SE HAN ENCENDIDO ANTERIORMENTE 
{
{
     int dec=13;
  for (dec=13;dec>0;dec--)//CICLO DECREMENTAL FOR QUE EMPIEZA DESDE EL ULTIMO PIN HACIA EL PIN 0 
  digitalWrite(leds[dec],HIGH);
  delay(200); 
    digitalWrite(leds[dec],LOW);
  delay(200);

}
  }

  void segundo_juego()// SEGUNDO CICLO DE JUEGO DE LUCES LOS CUALES EN FORMA DE ESCALERA SE ENCENDARAN Y APAGARAN LOS LEDS CABE RECALCAR QUE SE QUEDARAN PRENDIDOS CONFORME SIGA EL CICLO Y SE APAGARAN DESPUES DE HABERSE ENCENDIDO TODOS
{
     int dec=13;
  for (dec=13;dec>0;dec--) //CICLO DECREMENTAL ACUMULADO 
{
  digitalWrite(leds[dec],HIGH);//ENCENDERA A TODOS LOS LEDS EN ORDEN Y LOS MANTENDRA PRENDIDOS HASTA QUE EL CICLO SIGUIENTE LOS APAGUE
  delay(200); 
}
  }


  


void loop() {


primer_juego();//LLAMADO AL PRIMER CICLO
segundo_juego();//LAMADO AL SEGUNDO CICLO
tercer_juego();//LAMADO AL TERCER CICLO

    
}
